# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 00:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('prod_codigo', models.BigIntegerField(db_column='prod_codigo', primary_key=True, serialize=False)),
                ('prod_alias', models.CharField(db_column='prod_alias', max_length=50)),
                ('prod_descricao', models.CharField(db_column='prod_descricao', max_length=255)),
                ('prod_valor_venda', models.DecimalField(db_column='prod_valor_venda', decimal_places=2, max_digits=13)),
                ('prod_valor_compra', models.DecimalField(db_column='prod_valor_compra', decimal_places=2, max_digits=13)),
                ('prod_peso_b', models.DecimalField(db_column='prod_peso_b', decimal_places=2, max_digits=13)),
                ('prod_peso_l', models.DecimalField(db_column='prod_peso_l', decimal_places=2, max_digits=13)),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'managed': True,
                'db_table': 'produto',
            },
        ),
    ]
